name: CI Pipeline ðŸš§

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    # Remove unnecessary files to free up disk space
    - name: Free Disk Space (Manual Cleanup)
      run: |
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    # 2. Download code
    - name: Checkout code
      uses: actions/checkout@v3

    # 3. Python config
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    # 4. Build Docker
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag rag-app:test